import {fetchQuery} from 'convex/nextjs';
import {convexAuthNextjsToken} from '@convex-dev/auth/nextjs/server';
import {PDFDocument, rgb, StandardFonts} from 'pdf-lib';
import {api} from '@/convex/_generated/api';
import {Id} from '@/convex/_generated/dataModel';

export const dynamic = 'force-dynamic';

type PdfData = NonNullable<Awaited<ReturnType<typeof fetchQuery<typeof api.tickets.getForPdf>>>>;

async function buildPdf(data: PdfData, qrBytes: ArrayBuffer): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const page = doc.addPage([595.28, 841.89]); // A4
  const {width, height} = page.getSize();

  const regular = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);

  const dark = rgb(0.08, 0.08, 0.08);
  const muted = rgb(0.5, 0.5, 0.5);
  const orange = rgb(0.98, 0.45, 0.09);
  const divider = rgb(0.88, 0.88, 0.88);
  const white = rgb(1, 1, 1);
  const green = rgb(0.13, 0.7, 0.36);
  const blue = rgb(0.22, 0.49, 0.91);

  // Header band
  page.drawRectangle({x: 0, y: height - 80, width, height: 80, color: dark});
  page.drawText('TICKOCK', {x: 50, y: height - 52, size: 22, font: bold, color: white});

  const statusColor = data.ticket.status === 'confirmed' ? green : blue;
  const statusLabel = data.ticket.status === 'confirmed' ? 'CONFIRMED' : 'USED';
  page.drawText(statusLabel, {x: width - 140, y: height - 52, size: 11, font: bold, color: statusColor});

  // Event title
  const titleSize = data.event.title.length > 38 ? 16 : 21;
  page.drawText(data.event.title, {
    x: 50, y: height - 118, size: titleSize, font: bold, color: dark, maxWidth: 430,
  });

  // Date / Time / Venue
  const dateStr = new Date(data.event.date).toLocaleDateString('en-US', {
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric',
  });
  page.drawText(dateStr, {x: 50, y: height - 148, size: 11, font: regular, color: muted});

  const timeStr = `${data.event.startTime}${data.event.endTime ? ` – ${data.event.endTime}` : ''} (${data.event.timezone})`;
  page.drawText(timeStr, {x: 50, y: height - 165, size: 11, font: regular, color: muted});

  const venueStr = `${data.event.venue.name} · ${data.event.venue.address}, ${data.event.venue.city}`;
  page.drawText(venueStr, {x: 50, y: height - 182, size: 11, font: regular, color: muted, maxWidth: 430});

  // Divider 1
  page.drawLine({start: {x: 50, y: height - 205}, end: {x: width - 50, y: height - 205}, thickness: 0.5, color: divider});

  // Tier + Attendee columns
  page.drawText('TICKET TIER', {x: 50, y: height - 228, size: 8, font: bold, color: muted});
  page.drawText('ATTENDEE', {x: 290, y: height - 228, size: 8, font: bold, color: muted});

  page.drawText(data.tier.name, {x: 50, y: height - 248, size: 14, font: bold, color: dark});
  const buyerName = data.buyer.name ?? data.buyer.email;
  page.drawText(buyerName, {x: 290, y: height - 248, size: 14, font: bold, color: dark, maxWidth: 240});

  const priceLabel = data.tier.price === 0 ? 'Free' : `${data.tier.price} ${data.tier.currency}`;
  page.drawText(priceLabel, {x: 50, y: height - 266, size: 10, font: regular, color: muted});
  if (data.buyer.name) {
    page.drawText(data.buyer.email, {x: 290, y: height - 266, size: 10, font: regular, color: muted, maxWidth: 240});
  }

  // Divider 2
  page.drawLine({start: {x: 50, y: height - 290}, end: {x: width - 50, y: height - 290}, thickness: 0.5, color: divider});

  // Ticket number (left) + QR (right)
  page.drawText('TICKET NUMBER', {x: 50, y: height - 315, size: 8, font: bold, color: orange});

  if (data.ticket.ticketNumber) {
    page.drawText(data.ticket.ticketNumber, {
      x: 50, y: height - 350, size: 44, font: bold, color: dark,
    });
  }

  page.drawText('Present this number or the QR code at entry', {
    x: 50, y: height - 408, size: 9, font: regular, color: muted,
  });

  // QR code image
  try {
    const qrImage = await doc.embedPng(qrBytes);
    const qrSize = 155;
    page.drawImage(qrImage, {
      x: width - 50 - qrSize,
      y: height - 315 - qrSize,
      width: qrSize,
      height: qrSize,
    });
  } catch {
    // skip if QR fetch failed
  }

  // Divider 3
  page.drawLine({start: {x: 50, y: height - 490}, end: {x: width - 50, y: height - 490}, thickness: 0.5, color: divider});

  // Footer
  page.drawText(`Ticket ID: ${data.ticket._id}`, {
    x: 50, y: height - 510, size: 8, font: regular, color: muted,
  });
  page.drawText('Generated by TickOck · This ticket is non-transferable', {
    x: 50, y: height - 524, size: 8, font: regular, color: muted,
  });

  return doc.save();
}

export async function GET(_request: Request, {params}: {params: {id: string}}) {
  const token = await convexAuthNextjsToken();
  if (!token) {
    return new Response('Unauthorized', {status: 401});
  }

  const data = await fetchQuery(
    api.tickets.getForPdf,
    {ticketId: params.id as Id<'tickets'>},
    {token},
  );

  if (!data) {
    return new Response('Not found', {status: 404});
  }

  if (data.ticket.status !== 'confirmed' && data.ticket.status !== 'used') {
    return new Response('Ticket is not active', {status: 403});
  }

  const qrUrl = `https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=${encodeURIComponent(data.ticket.qrData)}&format=png&margin=1`;
  const qrRes = await fetch(qrUrl);
  const qrBytes = await qrRes.arrayBuffer();

  const pdfBytes = await buildPdf(data, qrBytes);

  const filename = `ticket-${data.ticket.ticketNumber ?? data.ticket._id.slice(-8)}.pdf`;

  return new Response(Buffer.from(pdfBytes), {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `inline; filename="${filename}"`,
      'Cache-Control': 'no-store',
    },
  });
}
